// <auto-generated />
namespace Project.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedtblUsersandtblImagestoDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtblUsersandtblImagestoDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202003201430496_added tblUsers and tblImages to DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
